#!/bin/bash

## KEYSTONE

export OS_SERVICE_ENDPOINT=http://${HOST_NAME}:35357/v2.0
export OS_SERVICE_TOKEN=${ADMIN_TOKEN}

#echo "=> Creating Keystone user"
#keystone user-create --name=keystone --pass=${KEYSTONE_PASS} --email=keystone@${EMAIL_ADDRESS}
#keystone user-role-add --user=keystone --tenant=service --role=admin
#echo "=> Done!"


## Create tenants, users, and roles

keystone tenant-create --name admin --description "Admin Tenant"
keystone user-create --name admin --pass ${ADMIN_PASS} --email admin@${EMAIL_ADDRESS}
keystone role-create --name admin
keystone user-role-add --user admin --tenant admin --role admin
keystone tenant-create --name demo --description "Demo Tenant"
keystone user-create --name demo --tenant demo --pass ${DEMO_PASS} --email demo@${EMAIL_ADDRESS}
keystone tenant-create --name service --description "Service Tenant"

## Create the service entity and API endpoints

keystone service-create --name keystone --type identity \
--description "OpenStack Identity"

keystone endpoint-create \
--service-id $(keystone service-list | awk '/ identity / {print $2}') \
--publicurl http://${HOST_NAME}::5000/v2.0 \
--internalurl http://${HOST_NAME}:5000/v2.0 \
--adminurl http://${HOST_NAME}:35357/v2.0 \
--region regionOne

## Tests

# http://docs.openstack.org/juno/install-guide/install/apt/content/keystone-verify.html


## GLANCE

