#!/bin/bash

mkdir /etc/openstack-dashboard
ln -s /opt/openstack/services/horizon/openstack_dashboard/local/local_settings.py.example /etc/openstack-dashboard/local_settings.py

cd /opt/openstack/services/horizon
source bin/activate
./manage.py make_web_conf --wsgi
./manage.py make_web_conf --apache > /etc/httpd/conf/horizon.conf
deactivate

## The followong two lines are currently unused
sed -i '/LoadModule\ foo_module/a LoadModule\ wsgi_module\ modules/mod_wsgi.so' \
  /etc/httpd/conf/httpd.conf
cat /etc/httpd/conf/horizon.conf >> /etc/httpd/conf/httpd.conf

echo "Updating local_settings.py file..."
sed -i -e "s/^OPENSTACK_HOST.*/OPENSTACK_HOST = \"${KEYSTONE_API_IP}\"/g" \
  /etc/openstack-dashboard/local_settings.py

sed -i -e "s/^ALLOWED_HOSTS.*/ALLOWED_HOSTS = \[\'\*\'\]/g" \
  /etc/openstack-dashboard/local_settings.py

sed -i -e "s/^OPENSTACK_KEYSTONE_URL.*/OPENSTACK_KEYSTONE_URL = \"http:\/\/%s:5000\/v3\" % OPENSTACK_HOST/g" \
  /etc/openstack-dashboard/local_settings.py

sed -i -e "s/^#OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT.*/OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True/g" \
  /etc/openstack-dashboard/local_settings.py

sed -i -e "s/^#OPENSTACK_KEYSTONE_DEFAULT_DOMAIN.*/OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = 'default'/g" \
  /etc/openstack-dashboard/local_settings.py

sed -i -e "s/^#OPENSTACK_API_VERSIONS.*/OPENSTACK_API_VERSIONS = {/g" \
  /etc/openstack-dashboard/local_settings.py

sed -i -e '/OPENSTACK_API_VERSIONS/a }' \
  /etc/openstack-dashboard/local_settings.py

sed -i -e '/OPENSTACK_API_VERSIONS/a     "image": 2,' \
  /etc/openstack-dashboard/local_settings.py

sed -i -e '/OPENSTACK_API_VERSIONS/a     "volume": 2,' \
  /etc/openstack-dashboard/local_settings.py

sed -i -e '/OPENSTACK_API_VERSIONS/a     "identity": 3,' \
  /etc/openstack-dashboard/local_settings.py

echo "Starting horizon using supervisord..."
exec /usr/bin/supervisord -n
