#!/bin/bash

echo "Removing cinder DB..."
rm /var/lib/cinder/cinder.sqlite

echo "Updating conf file..."
configparse.py

export OS_PROJECT_DOMAIN_NAME=default
export OS_USER_DOMAIN_NAME=default
export OS_PROJECT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=${ADMIN_PASS}
export OS_AUTH_URL=http://${KEYSTONE_HOST_IP}:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2

endpoint=`openstack endpoint list -f csv -q |grep cinder`

if [ -z "$endpoint" ]
then
    echo ">>>>>>> Endpoint not yet created"
    echo "Creating database"
    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "CREATE DATABASE cinder;"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost' \
            IDENTIFIED BY '${CINDER_DBPASS}';"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%' \
            IDENTIFIED BY '${CINDER_DBPASS}'"


    echo "Creating Cinder user..."
    openstack user create --domain default --password ${CINDER_PASS} cinder

    openstack role add --project service --user cinder admin

    echo "Registering Cinder API and EndPoints..."
    openstack service create --name cinder \
        --description "OpenStack Block Storage" volume

    openstack service create --name cinderv2 \
        --description "OpenStack Block Storage" volumev2

    openstack endpoint create --region RegionOne \
        volume public http://${KEYSTONE_HOST_IP}:8776/v1/%\(tenant_id\)s

    openstack endpoint create --region RegionOne \
        volume internal http://${KEYSTONE_HOST_IP}:8776/v1/%\(tenant_id\)s

    openstack endpoint create --region RegionOne \
        volume admin http://${KEYSTONE_HOST_IP}:8776/v1/%\(tenant_id\)s


    openstack endpoint create --region RegionOne \
        volumev2 public http://${KEYSTONE_HOST_IP}:8776/v2/%\(tenant_id\)s

    openstack endpoint create --region RegionOne \
        volumev2 internal http://${KEYSTONE_HOST_IP}:8776/v2/%\(tenant_id\)s

    openstack endpoint create --region RegionOne \
        volumev2 admin http://${KEYSTONE_HOST_IP}:8776/v2/%\(tenant_id\)s

else

    if [[ $endpoint == *"ERROR"* ]]
    then
        echo ">>>>>>> Cannot connect to Keystone"
        exit
    else
        echo ">>>>>>> Endpoint already created"
    fi
fi

echo "Create database tables"
cinder-manage db sync

echo "Starting cinder using supervisord..."
exec /usr/bin/supervisord -n
