#!/bin/bash

echo "Setting up horizon"

echo "Updating local_settings.py file..."
sed -i -e "s/^OPENSTACK_HOST.*/OPENSTACK_HOST = \"${KEYSTONE_HOST_IP}\"/g" /etc/openstack-dashboard/local_settings.py
sed -i -e "s/^ALLOWED_HOSTS.*/ALLOWED_HOSTS = \[\'\*\'\]/g" /etc/openstack-dashboard/local_settings.py

echo "Starting horizon..."
exec /usr/bin/supervisord -n
