#!/bin/bash

echo "Updating local_settings.py file..."
sed -i -e "s/^OPENSTACK_HOST.*/OPENSTACK_HOST = \"${KEYSTONE_HOST_IP}\"/g" /etc/openstack-dashboard/local_settings.py
sed -i -e "s/^ALLOWED_HOSTS.*/ALLOWED_HOSTS = \[\'\*\'\]/g" /etc/openstack-dashboard/local_settings.py
sed -i -e "s/^#OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT.*/OPENSTACK_KEYSTONE_MULTIDOMAIN_SUPPORT = True/g" /etc/openstack-dashboard/local_settings.py
sed -i -e "s/^#OPENSTACK_KEYSTONE_DEFAULT_DOMAIN.*/OPENSTACK_KEYSTONE_DEFAULT_DOMAIN = 'default'/g" /etc/openstack-dashboard/local_settings.py
sed -i -e "s/^OPENSTACK_KEYSTONE_DEFAULT_ROLE.*/OPENSTACK_KEYSTONE_DEFAULT_ROLE = \"user\"/g" /etc/openstack-dashboard/local_settings.py


echo "Starting horizon using supervisord..."
exec /usr/bin/supervisord -n
