#!/bin/bash

echo "Setting up murano..."

service murano start >/dev/null 2>&1

echo "Removing murano DB"
rm /var/lib/murano/murano.db

echo "Updating conf file..."
python3 /usr/local/bin/configparse.py

echo "Restarting murano"
service murano restart >/dev/null 2>&1

echo "Create database..."
echo "=> Creating ${SERVICE} database"
echo "=> DB ${MYSQL_DB}"
echo "=> User ${MYSQL_USER}"
echo "=> Password ${MYSQL_PASSWORD}"

mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "CREATE DATABASE murano;"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON murano.* TO 'murano'@'localhost' \
IDENTIFIED BY '${MURANO_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON murano.* TO 'murano'@'${HOST_NAME}' \
IDENTIFIED BY '${MURANO_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON murano.* TO 'murano'@'%' \
IDENTIFIED BY '${MURANO_DBPASS}'"

echo "Create database tables"
su -s /bin/sh -c "murano-manage db_sync" murano

echo "Stopping murano"
service murano stop >/dev/null 2>&1

echo "Starting murano using supervisord..."
exec /usr/bin/supervisord -n