#!/bin/bash

echo "Setting up cinder..."

service cinder start >/dev/null 2>&1

echo "Removing cinder DB"
rm /var/lib/cinder/cinder.db

echo "Updating conf file..."
python3 /usr/local/bin/configparse.py

echo "Restarting cinder"
service cinder restart >/dev/null 2>&1

echo "Create database..."
echo "=> Creating ${SERVICE} database"
echo "=> DB ${MYSQL_DB}"
echo "=> User ${MYSQL_USER}"
echo "=> Password ${MYSQL_PASSWORD}"

mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "CREATE DATABASE cinder;"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost' \
IDENTIFIED BY '${CINDER_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'${HOST_NAME}' \
IDENTIFIED BY '${CINDER_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%' \
IDENTIFIED BY '${CINDER_DBPASS}'"

echo "Create database tables"
su -s /bin/sh -c "cinder-manage db_sync" cinder

echo "Stopping cinder"
service cinder stop >/dev/null 2>&1

echo "Starting cinder using supervisord..."
exec /usr/bin/supervisord -n