#!/bin/bash

echo "Updating conf file..."
configparse.py



echo "Creating database..."
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} \
      -e "CREATE DATABASE mistral;"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} \
      -e "GRANT ALL PRIVILEGES ON mistral.* TO 'mistral'@'localhost' IDENTIFIED BY '${MISTRAL_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} \
      -e "GRANT ALL PRIVILEGES ON mistral.* TO 'mistral'@'${HOST_NAME}' IDENTIFIED BY '${MISTRAL_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} \
      -e "GRANT ALL PRIVILEGES ON mistral.* TO 'mistral'@'%' IDENTIFIED BY '${MISTRAL_DBPASS}'"

echo "Creating Mistral user..."
keystone user-create --name mistral --pass ${MISTRAL_PASS} --email=mistral@${EMAIL_ADDRESS}
keystone user-role-add --user mistral --tenant service --role admin

echo "Registering Mistral API and EndPoints..."
keystone service-create --name mistral --type workflowv2 --description "OpenStack Mistral"
keystone endpoint-create \
  --service-id $(keystone service-list | awk '/ workflowv2 / {print $2}') \
  --publicurl http://${HOST_IP}:8989/v2 \
  --adminurl http://${HOST_IP}:8989/v2 \
  --internalurl http://${HOST_IP}:8989/v2 \
  --region regionOne


echo "Create database tables"
python /mistral/tools/sync_db.py --config-file /mistral/etc/mistral.conf


echo "Starting mistral using supervisord..."
exec /usr/bin/supervisord -n
