#!/bin/bash

echo "Removing nova DB..."
rm /var/lib/nova/nova.sqlite

echo "Updating conf file..."
configparse.py

export OS_USERNAME=admin
export OS_PASSWORD=${ADMIN_PASS} 
export OS_TENANT_NAME=admin
export OS_AUTH_URL=http://${KEYSTONE_HOST_IP}:35357/v2.0

endpoint=`openstack endpoint list -f csv -q |grep nova`

if [ -z "$endpoint" ]
then
    echo ">>>>>>> Endpoint not created"
    echo "Creating database"
    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "CREATE DATABASE nova;"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' \
            IDENTIFIED BY '${NOVA_DBPASS}';"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' \
            IDENTIFIED BY '${NOVA_DBPASS}';"
    
    echo "Creating Nova user..."
    openstack user create --password ${NOVA_PASS} nova
    
    openstack role add --project service --user nova admin
    
    echo "Registering Nova API and EndPoints..."
    openstack service create --type compute \
        --description "OpenStack Compute" nova

    openstack endpoint create \
        --publicurl http://${KEYSTONE_HOST_IP}:8774/v2/%\(tenant_id\)s \
        --internalurl http://${KEYSTONE_HOST_IP}:8774/v2/%\(tenant_id\)s \
        --adminurl http://${KEYSTONE_HOST_IP}:8774/v2/%\(tenant_id\)s \
        --region RegionOne \
        compute

    echo "Testing Nova..."
    nova service-list
    nova endpoints

else

    if [[ $endpoint == *"ERROR"* ]]
    then
        echo ">>>>>>> Cannot connect to Keystone"
        exit
    else
        echo ">>>>>>> Endpoint already created"
        echo "Testing Nova..."
        nova service-list
        nova endpoints
        nova image-list
    fi
fi

echo "Updating database tables"
nova-manage db sync

echo "Starting nova using supervisord..."
exec /usr/bin/supervisord -n
