#!/bin/bash

echo "Setting up glance"

service glance-registry restart >/dev/null 2>&1
service glance-api restart >/dev/null 2>&1

echo "Removing glance DB..."
rm /var/lib/glance/glance.sqlite

echo "Updating conf file..."
python3 /usr/local/bin/configparser.py

echo "Restarting glance"
service glance-registry restart >/dev/null 2>&1
service glance-api restart >/dev/null 2>&1

mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "CREATE DATABASE glance;"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' \
IDENTIFIED BY '${GLANCE_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'${HOST_NAME}' \
IDENTIFIED BY '${GLANCE_DBPASS}';"
mysql -h${MYSQL_DB} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' \
IDENTIFIED BY '${GLANCE_DBPASS}'"

echo "Create database tables"
su -s /bin/sh -c "glance-manage db_sync" glance

echo "Stopping glance"
service glance-registry stop >/dev/null 2>&1
service glance-api stop >/dev/null 2>&1

echo "Starting glance using supervisord..."
exec /usr/bin/supervisord -n