#!/bin/bash

export OS_URL=http://${MYSQL_HOST_IP}:35357/v3
export OS_TOKEN=${ADMIN_TOKEN}
export OS_IDENTITY_API_VERSION=3

openstack domain create --description "Default Domain" default

openstack project create --domain default --description "Admin Project" admin
openstack user create --domain default --password ${ADMIN_TOKEN} admin
openstack role create admin
openstack role add --project admin --user admin admin

openstack project create --domain default --description "Service Project" service

openstack project create --domain default --description "Demo Project" demo
openstack user create --domain default --password ${ADMIN_TOKEN} demo
openstack role create user
openstack role add --project demo --user demo user

openstack service create --name keystone --description "OpenStack Identity" identity
openstack endpoint create --region RegionOne identity public http://192.168.1.250:5000/v3
openstack endpoint create --region RegionOne identity internal http://192.168.1.250:5000/v3
openstack endpoint create --region RegionOne identity admin http://192.168.1.250:35357/v3

unset OS_TOKEN OS_URL
export OS_PASSWORD=${ADMIN_TOKEN}

openstack --os-auth-url http://${KEYSTONE_HOST_IP}:35357/v3 \
  --os-project-domain-name default --os-user-domain-name default \
  --os-project-name admin --os-username admin token issue

echo "#END"
