#!/bin/bash

export OS_URL=http://${MYSQL_HOST_IP}:35357/v2.0
export OS_TOKEN=${ADMIN_TOKEN}

openstack service create --type identity \
      --description "OpenStack Identity" keystone

openstack endpoint create \
      --publicurl http://${KEYSTONE_HOST_IP}:5000/v2.0 \
      --internalurl http://${KEYSTONE_HOST_IP}:5000/v2.0 \
      --adminurl http://${KEYSTONE_HOST_IP}:35357/v2.0 \
      --region RegionOne \
      identity

openstack project create --description "Admin Project" admin

openstack user create --password ${ADMIN_PASS} admin

openstack role create admin

openstack role add --project admin --user admin admin

openstack project create --description "Service Project" service

openstack project create --description "Demo Project" demo

openstack user create --password ${DEMO_PASS} demo

openstack role create _member_

openstack role add --project demo --user demo _member_

unset OS_TOKEN OS_URL

openstack --os-auth-url http://${KEYSTONE_HOST_IP}:35357 \
  --os-project-name admin --os-username admin --os-password ${ADMIN_PASS} \
  token issue

echo "#END"
