FROM base/arch
MAINTAINER epheo <shaddock@epheo.eu>

# Base Archlinux docker image is outdated crap
# We should do a Jenkins job to autobuild and propose dailybuilds.
#

RUN pacman -Syu python2-virtualenv git

RUN mkdir /opt/openstack/
WORKDIR   /opt/openstack/


RUN exit 0
