#!/bin/bash

echo "Removing glance DB..."
rm /var/lib/glance/glance.sqlite

echo "Updating conf file..."
configparse.py

export OS_USERNAME=admin
export OS_PASSWORD=${ADMIN_PASS}
export OS_TENANT_NAME=admin
export OS_AUTH_URL=http://${KEYSTONE_HOST_IP}:35357/v2.0

endpoint=`openstack endpoint list -f csv -q |grep glance`

if [ -z "$endpoint" ]
then
    echo ">>>>>>> Endpoint not yet created"
    echo "Creating database"
    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "CREATE DATABASE glance;"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' \
            IDENTIFIED BY '${GLANCE_DBPASS}';"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' \
            IDENTIFIED BY '${GLANCE_DBPASS}'"


    echo "Creating Glance user..."
    openstack user create --password ${GLANCE_PASS} glance

    openstack role add --project service --user glance admin

    echo "Registering Glance API and EndPoints..."
    openstack service create --type image \
        --description "OpenStack Image service" glance

    openstack endpoint create \
        --publicurl http://${KEYSTONE_HOST_IP}:9292 \
        --internalurl http://${KEYSTONE_HOST_IP}:9292 \
        --adminurl http://${KEYSTONE_HOST_IP}:9292 \
        --region RegionOne \
        image

    # mkdir /tmp/images
    # wget -P /tmp/images http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img
    # glance image-create --name "cirros-0.3.3-x86_64" --file /tmp/images/cirros-0.3.3-x86_64-disk.img \
        # --disk-format qcow2 --container-format bare --visibility public --progress
    # glance image-list

else

    if [[ $endpoint == *"ERROR"* ]]
    then
        echo ">>>>>>> Cannot connect to Keystone"
        exit
    else
        echo ">>>>>>> Endpoint already created"
    fi
fi

echo "Updating database tables"
glance-manage db_sync

echo "Starting glance using supervisord..."
exec /usr/bin/supervisord -n
