#!/bin/bash

echo "Removing glance DB..."
rm /var/lib/glance/glance.sqlite

echo "Updating conf file..."
configparse.py

export OS_PROJECT_DOMAIN_NAME=default
export OS_USER_DOMAIN_NAME=default
export OS_PROJECT_NAME=admin
export OS_USERNAME=admin
export OS_PASSWORD=${ADMIN_PASS}
export OS_AUTH_URL=http://${KEYSTONE_HOST_IP}:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2

endpoint=`openstack endpoint list -f csv -q |grep glance`

if [ -z "$endpoint" ]
then
    echo ">>>>>>> Endpoint not yet created"
    echo "Creating database"
    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "CREATE DATABASE glance;"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' \
            IDENTIFIED BY '${GLANCE_DBPASS}';"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' \
            IDENTIFIED BY '${GLANCE_DBPASS}'"


    echo "Creating Glance user..."
    openstack user create --domain default --password ${GLANCE_PASS} glance

    openstack role add --project service --user glance admin

    echo "Registering Glance API and EndPoints..."
    openstack service create --name glance \
        --description "OpenStack Image" image

    openstack endpoint create --region RegionOne \
        image public http://${GLANCE_HOST_IP}:9292

    openstack endpoint create --region RegionOne \
        image internal http://${GLANCE_HOST_IP}:9292

    openstack endpoint create --region RegionOne \
        image admin http://${GLANCE_HOST_IP}:9292

else

    if [[ $endpoint == *"ERROR"* ]]
    then
        echo ">>>>>>> Cannot connect to Keystone"
        exit
    else
        echo ">>>>>>> Endpoint already created"
    fi
fi

echo "Updating database tables"
glance-manage db_sync

echo "Starting glance using supervisord..."
exec /usr/bin/supervisord -n
