#!/bin/bash

echo "Updating conf file..."
configparse.py

export OS_USERNAME=admin
export OS_PASSWORD=${ADMIN_PASS}
export OS_TENANT_NAME=admin
export OS_AUTH_URL=http://${KEYSTONE_HOST_IP}:35357/v2.0

endpoint=`openstack endpoint list -f csv -q |grep neutron`

if [ -z "$endpoint" ]
then
    echo ">>>>>>> Endpoint not created"
    echo "Creating database neutron"
    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "CREATE DATABASE neutron;"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' \
            IDENTIFIED BY '${NEUTRON_DBPASS}';"

    mysql \
        -h${MYSQL_HOST_IP} \
        -u${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' \
            IDENTIFIED BY '${NEUTRON_DBPASS}';"

    echo "Creating Neutron user..."
    openstack user create --password ${NEUTRON_PASS} neutron

    openstack role add --project service --user neutron admin

    echo "Registering Neutron API and EndPoints..."
    openstack service create --name neutron \
        --description "OpenStack Networking" network

    openstack endpoint create \
        --publicurl http://${KEYSTONE_HOST_IP}:9696 \
        --internalurl http://${KEYSTONE_HOST_IP}:9696 \
        --adminurl http://${KEYSTONE_HOST_IP}:9696 \
        --region RegionOne \
        network

    echo "Testing Neutron..."
    #neutron ext-list

else

    if [[ $endpoint == *"ERROR"* ]]
    then
        echo ">>>>>>> Cannot connect to Keystone"
        exit
    else
        echo ">>>>>>> Endpoint already created"
        echo "Testing Neutron..."
        #neutron ext-list
    fi
fi

echo "Create databases tables"
neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

echo "Starting nova using supervisord..."
exec /usr/bin/supervisord -n
